// Ubiklos sample data
// Workers, oficios, municipios, jobs

const OFICIOS = [
  { id: "plomero", label: "Plomero" },
  { id: "electricista", label: "Electricista" },
  { id: "albanil", label: "Albañil" },
  { id: "pintor", label: "Pintor" },
  { id: "cerrajero", label: "Cerrajero" },
];

const MUNICIPIOS = [
  { id: "libertador", label: "Libertador" },
  { id: "chacao", label: "Chacao" },
  { id: "baruta", label: "Baruta" },
  { id: "hatillo", label: "El Hatillo" },
  { id: "sucre", label: "Sucre" },
];

// Deterministic initial state. Times relative to "today" 2026-05-18.
const TODAY = new Date(2026, 4, 18).getTime();
const daysAgo = (n) => new Date(TODAY - n * 86400000).toISOString();

// Worker model:
//   verified — cédula approved (badge "Cédula verificada")
//   whatsapp — OTP confirmed (always true for these — they registered)
//   location — GPS confirmed
//   activeDays — days since last login
//   confirmedJobs — count of jobs both parties confirmed
//   selfReportedJobs — worker said done, client didn't confirm
//   rating — average; null if <3 ratings
//   ratingsCount — number of ratings
//   memberSince — ISO date
//   bio — short description
//   jobs — array of {id, title, desc, photo, date, confirmed: bool, clientName?}
//   reviews — array of {id, stars, text, clientName, date}
//
// Photos are described by token — we render a placeholder with a label,
// or use a generated gradient/stripe pattern. No hand-drawn SVG illustrations.

const WORKERS = [
  {
    id: "andres-mendoza",
    slug: "andres",
    name: "Andrés Mendoza",
    initials: "AM",
    photoTone: "#7B7AC4",
    oficios: ["plomero"],
    municipios: ["chacao", "baruta"],
    verified: true,
    whatsapp: true,
    location: true,
    activeDays: 0, // hoy
    confirmedJobs: 12,
    selfReportedJobs: 3,
    rating: 4.8,
    ratingsCount: 9,
    memberSince: "2025-08-12",
    phone: "+58 412 000 0142",
    bio: "Plomero con 14 años de oficio. Trabajo fugas, instalaciones de baño completo y calentadores. Llego puntual y cobro lo justo. Atiendo Chacao y Baruta, salidas a otras zonas conversables.",
    jobs: [
      { id: "j1", title: "Cambio de tubería en cocina", desc: "Tubería de cobre. 4 horas de trabajo. Residencia Los Palos Grandes.", photo: "bathroom", date: daysAgo(8), confirmed: true, clientName: "Sra. Patricia" },
      { id: "j2", title: "Instalación de calentador", desc: "Calentador eléctrico 80L. Edif. La Castellana.", photo: "heater", date: daysAgo(22), confirmed: true, clientName: "Familia Briceño" },
      { id: "j3", title: "Fuga en baño principal", desc: "Pase de tubería bajo el lavamanos.", photo: "pipe", date: daysAgo(34), confirmed: true, clientName: "Sr. Eduardo" },
      { id: "j4", title: "Reemplazo de pocetas", desc: "Dos baños completos.", photo: "toilet", date: daysAgo(51), confirmed: false },
      { id: "j5", title: "Reparación de llaves", desc: "Cocina y baño visita.", photo: "tap", date: daysAgo(72), confirmed: true, clientName: "Sra. Carmen" },
    ],
    reviews: [
      { id: "r1", stars: 5, text: "Puntual y trabajo limpio. Dejó todo recogido.", clientName: "Patricia G.", date: daysAgo(7) },
      { id: "r2", stars: 5, text: "Resolvió la fuga rápido. Cobró lo acordado.", clientName: "Eduardo M.", date: daysAgo(33) },
      { id: "r3", stars: 4, text: "Buen trabajo, llegó un poco tarde.", clientName: "Carmen R.", date: daysAgo(70) },
    ],
  },
  {
    id: "yusneidy-perez",
    slug: "yusneidy",
    name: "Yusneidy Pérez",
    initials: "YP",
    photoTone: "#E89F8A",
    oficios: ["pintor"],
    municipios: ["sucre", "libertador"],
    verified: true,
    whatsapp: true,
    location: true,
    activeDays: 2,
    confirmedJobs: 7,
    selfReportedJobs: 2,
    rating: 4.6,
    ratingsCount: 5,
    memberSince: "2025-11-03",
    phone: "+58 414 000 0317",
    bio: "Pintora residencial. Trabajo paredes interiores, esmalte en puertas y rejas, y exteriores hasta 2 pisos. Equipo de 2 personas si el trabajo lo requiere.",
    jobs: [
      { id: "j1", title: "Apartamento completo, 3 cuartos", desc: "Pintura interior, 2 capas. Petare.", photo: "room", date: daysAgo(11), confirmed: true, clientName: "Sr. Luis" },
      { id: "j2", title: "Fachada de casa", desc: "Lavado y pintura exterior. El Cementerio.", photo: "facade", date: daysAgo(28), confirmed: true, clientName: "Familia Herrera" },
      { id: "j3", title: "Sala y comedor", desc: "Cambio de color. Quinta Crespo.", photo: "living", date: daysAgo(45), confirmed: true, clientName: "Sra. Marta" },
    ],
    reviews: [
      { id: "r1", stars: 5, text: "Muy ordenada, cubrió todos los muebles.", clientName: "Luis P.", date: daysAgo(10) },
      { id: "r2", stars: 4, text: "Buen acabado, pidió un día extra.", clientName: "Marta L.", date: daysAgo(44) },
    ],
  },
  {
    id: "carlos-rivero",
    slug: "carlos",
    name: "Carlos Rivero",
    initials: "CR",
    photoTone: "#5C7AC9",
    oficios: ["electricista"],
    municipios: ["baruta", "hatillo"],
    verified: true,
    whatsapp: true,
    location: true,
    activeDays: 0,
    confirmedJobs: 23,
    selfReportedJobs: 4,
    rating: 4.9,
    ratingsCount: 18,
    memberSince: "2025-04-22",
    phone: "+58 416 000 0822",
    bio: "Electricista certificado. Tableros, cortos, instalación de tomas, breakers, iluminación LED. 19 años en el oficio. Disponible fines de semana.",
    jobs: [
      { id: "j1", title: "Cambio de tablero principal", desc: "Quinta en La Lagunita. Tablero 24 polos.", photo: "panel", date: daysAgo(3), confirmed: true, clientName: "Sr. Rafael" },
      { id: "j2", title: "Iluminación de jardín", desc: "12 puntos LED exteriores.", photo: "light", date: daysAgo(14), confirmed: true, clientName: "Familia Salas" },
      { id: "j3", title: "Reparación de corto", desc: "Cocina de apartamento.", photo: "kitchen", date: daysAgo(19), confirmed: true, clientName: "Sra. Yolanda" },
      { id: "j4", title: "Instalación de aire acondicionado", desc: "Punto 220V + estructura.", photo: "ac", date: daysAgo(31), confirmed: true, clientName: "Sr. Antonio" },
      { id: "j5", title: "Cambio de breakers", desc: "Edificio en Las Mercedes.", photo: "breaker", date: daysAgo(42), confirmed: true, clientName: "Junta de cond." },
    ],
    reviews: [
      { id: "r1", stars: 5, text: "Profesional. Explicó todo y dejó plano del tablero.", clientName: "Rafael S.", date: daysAgo(2) },
      { id: "r2", stars: 5, text: "Llegó el sábado en la mañana, trabajo impecable.", clientName: "Yolanda P.", date: daysAgo(18) },
      { id: "r3", stars: 5, text: "Justo precio y rápido.", clientName: "Antonio R.", date: daysAgo(30) },
      { id: "r4", stars: 4, text: "Bien, aunque cobró un poco más que la cotización.", clientName: "Andrea M.", date: daysAgo(56) },
    ],
  },
  {
    id: "jose-luis-marin",
    slug: "jose-luis",
    name: "José Luis Marín",
    initials: "JM",
    photoTone: "#7DC6E8",
    oficios: ["albanil"],
    municipios: ["libertador"],
    verified: true,
    whatsapp: true,
    location: false,
    activeDays: 1,
    confirmedJobs: 4,
    selfReportedJobs: 1,
    rating: null,
    ratingsCount: 2,
    memberSince: "2026-01-18",
    phone: "+58 412 000 0907",
    bio: "Albañil. Friso, repello, levantamiento de paredes, reparación de filtraciones de techo. Trabajo con ayudante.",
    jobs: [
      { id: "j1", title: "Reparación de friso", desc: "Pared exterior 12m². San Bernardino.", photo: "wall", date: daysAgo(9), confirmed: true, clientName: "Sr. Pedro" },
      { id: "j2", title: "Levantamiento de pared", desc: "Divisor en sala. Bloques 15.", photo: "block", date: daysAgo(25), confirmed: true, clientName: "Sra. Iris" },
    ],
    reviews: [
      { id: "r1", stars: 5, text: "Trabajo serio.", clientName: "Pedro G.", date: daysAgo(8) },
      { id: "r2", stars: 4, text: "Bien hecho, tardó un día más.", clientName: "Iris M.", date: daysAgo(24) },
    ],
  },
  {
    id: "henry-quintero",
    slug: "henry",
    name: "Henry Quintero",
    initials: "HQ",
    photoTone: "#3A4566",
    oficios: ["cerrajero"],
    municipios: ["chacao"],
    verified: true,
    whatsapp: true,
    location: true,
    activeDays: 0,
    confirmedJobs: 18,
    selfReportedJobs: 2,
    rating: 5.0,
    ratingsCount: 14,
    memberSince: "2025-06-30",
    phone: "+58 414 000 0211",
    bio: "Cerrajero 24 horas. Apertura sin daño, copia de llaves, cambio de cilindros, cerraduras de seguridad. Atiendo emergencias en Chacao y alrededores.",
    jobs: [
      { id: "j1", title: "Apertura puerta principal", desc: "Sin daño, 20 min. Altamira.", photo: "door", date: daysAgo(1), confirmed: true, clientName: "Sra. Beatriz" },
      { id: "j2", title: "Cambio de cilindro alemán", desc: "Cilindro de alta seguridad.", photo: "lock", date: daysAgo(6), confirmed: true, clientName: "Sr. Jaime" },
      { id: "j3", title: "Cerradura electrónica", desc: "Instalación y configuración.", photo: "smart", date: daysAgo(15), confirmed: true, clientName: "Familia Núñez" },
    ],
    reviews: [
      { id: "r1", stars: 5, text: "Llegó en 30 min de madrugada. Tremendo servicio.", clientName: "Beatriz F.", date: daysAgo(0) },
      { id: "r2", stars: 5, text: "Cilindro de calidad, lo instaló rápido.", clientName: "Jaime O.", date: daysAgo(5) },
      { id: "r3", stars: 5, text: "Recomendado.", clientName: "Andrea N.", date: daysAgo(14) },
    ],
  },
  {
    id: "maria-alejandra-suarez",
    slug: "maria-alejandra",
    name: "María Alejandra Suárez",
    initials: "MS",
    photoTone: "#C77AC4",
    oficios: ["pintor"],
    municipios: ["baruta", "chacao"],
    verified: true,
    whatsapp: true,
    location: true,
    activeDays: 3,
    confirmedJobs: 2,
    selfReportedJobs: 0,
    rating: null,
    ratingsCount: 1,
    memberSince: "2026-03-10",
    phone: "+58 424 000 0488",
    bio: "Pintora. Acabados decorativos, esmalte, paredes texturizadas. Recién en Ubiklos, vengo trabajando con clientes referidos hace 6 años.",
    jobs: [
      { id: "j1", title: "Cuarto infantil con murales", desc: "Pintura base + figuras simples.", photo: "kids", date: daysAgo(20), confirmed: true, clientName: "Familia Rojas" },
      { id: "j2", title: "Esmalte de rejas", desc: "Frente de casa.", photo: "rails", date: daysAgo(34), confirmed: true, clientName: "Sra. Lourdes" },
    ],
    reviews: [],
  },
  {
    id: "wilmer-arteaga",
    slug: "wilmer",
    name: "Wilmer Arteaga",
    initials: "WA",
    photoTone: "#4F8C6A",
    oficios: ["plomero", "albanil"],
    municipios: ["libertador", "sucre"],
    verified: true,
    whatsapp: true,
    location: true,
    activeDays: 0,
    confirmedJobs: 15,
    selfReportedJobs: 5,
    rating: 4.7,
    ratingsCount: 11,
    memberSince: "2025-07-08",
    phone: "+58 412 000 0664",
    bio: "Plomero y albañil. Combino los dos oficios para trabajos de baño completo: pico, plomería, friso, cerámica. Ahorra contratar dos personas.",
    jobs: [
      { id: "j1", title: "Baño completo desde cero", desc: "Pico + plomería + cerámica.", photo: "bathfull", date: daysAgo(4), confirmed: true, clientName: "Sr. Gustavo" },
      { id: "j2", title: "Friso + nueva tubería", desc: "Pared dañada por humedad.", photo: "leak", date: daysAgo(17), confirmed: true, clientName: "Sra. Elena" },
      { id: "j3", title: "Reparación de poceta", desc: "Cambio de empaques y base.", photo: "toilet", date: daysAgo(29), confirmed: true, clientName: "Sr. Manuel" },
    ],
    reviews: [
      { id: "r1", stars: 5, text: "Hizo todo el baño en 5 días. Recomendado.", clientName: "Gustavo C.", date: daysAgo(3) },
      { id: "r2", stars: 4, text: "Trabajo bueno, el friso quedó algo grueso.", clientName: "Elena V.", date: daysAgo(16) },
    ],
  },
  {
    id: "deivis-mora",
    slug: "deivis",
    name: "Deivis Mora",
    initials: "DM",
    photoTone: "#D9A05B",
    oficios: ["electricista"],
    municipios: ["sucre", "libertador"],
    verified: true,
    whatsapp: true,
    location: true,
    activeDays: 5,
    confirmedJobs: 8,
    selfReportedJobs: 2,
    rating: 4.5,
    ratingsCount: 6,
    memberSince: "2025-10-14",
    phone: "+58 416 000 0123",
    bio: "Electricista. Instalaciones residenciales y pequeño comercio. Disponible en Petare, Caricuao y zonas cercanas.",
    jobs: [
      { id: "j1", title: "Tablero de bodega", desc: "Comercio en Petare. 12 puntos.", photo: "shop", date: daysAgo(13), confirmed: true, clientName: "Sr. Ramón" },
      { id: "j2", title: "Cambio de iluminación", desc: "Casa entera a LED.", photo: "led", date: daysAgo(26), confirmed: true, clientName: "Familia Castillo" },
    ],
    reviews: [
      { id: "r1", stars: 5, text: "Buen trabajo, llegó a la hora acordada.", clientName: "Ramón G.", date: daysAgo(12) },
      { id: "r2", stars: 4, text: "Bien, aunque dejó pintar a otro.", clientName: "Sara C.", date: daysAgo(25) },
    ],
  },
  {
    id: "luis-yepez",
    slug: "luis-yepez",
    name: "Luis Yépez",
    initials: "LY",
    photoTone: "#A07A4F",
    oficios: ["cerrajero"],
    municipios: ["baruta", "hatillo"],
    verified: true,
    whatsapp: true,
    location: false,
    activeDays: 8,
    confirmedJobs: 3,
    selfReportedJobs: 1,
    rating: null,
    ratingsCount: 2,
    memberSince: "2026-02-02",
    phone: "+58 414 000 0989",
    bio: "Cerrajero. Apertura, copias, cambio de cerraduras. Trabajo en Baruta y El Hatillo de lunes a sábado.",
    jobs: [
      { id: "j1", title: "Cambio de cerradura", desc: "Apartamento en Las Mercedes.", photo: "lock", date: daysAgo(18), confirmed: true, clientName: "Sra. Verónica" },
    ],
    reviews: [
      { id: "r1", stars: 4, text: "Bien, llegó tarde.", clientName: "Verónica G.", date: daysAgo(17) },
    ],
  },
  {
    id: "rocio-blanco",
    slug: "rocio",
    name: "Rocío Blanco",
    initials: "RB",
    photoTone: "#A06FB8",
    oficios: ["pintor", "albanil"],
    municipios: ["chacao", "baruta"],
    verified: true,
    whatsapp: true,
    location: true,
    activeDays: 1,
    confirmedJobs: 6,
    selfReportedJobs: 1,
    rating: 4.8,
    ratingsCount: 5,
    memberSince: "2025-09-05",
    phone: "+58 412 000 0732",
    bio: "Pintora y trabajos pequeños de albañilería. Especialidad en acabados de calidad y reparación de paredes con humedad. Trabajo sola, sin ayudantes.",
    jobs: [
      { id: "j1", title: "Reparación pared con humedad + pintura", desc: "Apartamento Los Palos Grandes.", photo: "humid", date: daysAgo(7), confirmed: true, clientName: "Sra. Lucía" },
      { id: "j2", title: "Pintura de cocina", desc: "Esmalte resistente a grasa.", photo: "kitchen", date: daysAgo(21), confirmed: true, clientName: "Sr. Diego" },
    ],
    reviews: [
      { id: "r1", stars: 5, text: "Detallista. Vale lo que cobra.", clientName: "Lucía R.", date: daysAgo(6) },
      { id: "r2", stars: 5, text: "Excelente acabado.", clientName: "Diego A.", date: daysAgo(20) },
    ],
  },
];

// Pending verification queue (for admin flow). These are NOT in WORKERS — admin
// can approve/reject; on approve they move into WORKERS in memory.
const PENDING_VERIFICATIONS = [
  {
    id: "pending-1",
    name: "Eduard Salazar",
    initials: "ES",
    photoTone: "#7B7AC4",
    cedula: "V-18.443.221",
    oficios: ["plomero"],
    municipios: ["sucre"],
    phone: "+58 412 000 0301",
    submitted: daysAgo(0),
    photoFront: "ok",
    photoBack: "ok",
    selfie: "ok",
    bio: "Plomero residencial. Especialidad en calentadores y bombas de agua.",
    flags: [],
  },
  {
    id: "pending-2",
    name: "Greisy Camacho",
    initials: "GC",
    photoTone: "#E89F8A",
    cedula: "V-22.108.987",
    oficios: ["pintor"],
    municipios: ["baruta", "chacao"],
    phone: "+58 414 000 0567",
    submitted: daysAgo(0),
    photoFront: "ok",
    photoBack: "ok",
    selfie: "blurry",
    bio: "Pintora residencial, 8 años de experiencia. Trabajo sola.",
    flags: ["Selfie con poca luz"],
  },
  {
    id: "pending-3",
    name: "Oswaldo Briceño",
    initials: "OB",
    photoTone: "#5C7AC9",
    cedula: "V-15.882.401",
    oficios: ["electricista", "plomero"],
    municipios: ["libertador"],
    phone: "+58 416 000 0234",
    submitted: daysAgo(1),
    photoFront: "ok",
    photoBack: "ok",
    selfie: "ok",
    bio: "Electricista con conocimientos básicos de plomería. 15 años de oficio.",
    flags: [],
  },
  {
    id: "pending-4",
    name: "Yusmary Toro",
    initials: "YT",
    photoTone: "#C77AC4",
    cedula: "V-26.554.118",
    oficios: ["cerrajero"],
    municipios: ["chacao", "sucre"],
    phone: "+58 424 000 0712",
    submitted: daysAgo(1),
    photoFront: "ok",
    photoBack: "reflective",
    selfie: "ok",
    bio: "Cerrajera. Apertura, copias y cerraduras.",
    flags: ["Reflejo en cédula reverso"],
  },
  {
    id: "pending-5",
    name: "Jhonny Pacheco",
    initials: "JP",
    photoTone: "#4F8C6A",
    cedula: "V-19.227.553",
    oficios: ["albanil"],
    municipios: ["hatillo"],
    phone: "+58 412 000 0859",
    submitted: daysAgo(2),
    photoFront: "ok",
    photoBack: "ok",
    selfie: "ok",
    bio: "Albañil. Trabajo en equipo de 3, manejamos obras pequeñas.",
    flags: [],
  },
];

// Initial contact loop state — pending follow-ups for the "client" persona.
// The user playing client will see one of these as a notification banner.
const PENDING_FOLLOWUPS = [
  {
    id: "fu-1",
    workerId: "andres-mendoza",
    contactedAt: daysAgo(2),
    status: "pending", // pending | rated | dismissed
  },
];

// Initial worker dashboard state (for the "trabajador" persona we simulate logged-in)
// We let user pick which worker to "be"; default is Andrés.
const CURRENT_WORKER_ID = "andres-mendoza";

// Pending confirmations for the current worker — clients that already said "lo contraté",
// awaiting worker's own "completado".
const PENDING_CONFIRMATIONS = [
  {
    id: "pc-1",
    workerId: "andres-mendoza",
    clientName: "Sra. Mariana",
    jobHint: "Fuga en cocina, El Rosal",
    contactedAt: daysAgo(3),
    clientConfirmed: true,
    workerConfirmed: false,
  },
  {
    id: "pc-2",
    workerId: "andres-mendoza",
    clientName: "Sr. Ricardo",
    jobHint: "Cambio de llave de paso, Los Caobos",
    contactedAt: daysAgo(5),
    clientConfirmed: true,
    workerConfirmed: false,
  },
];

window.UBIKLOS_DATA = {
  OFICIOS,
  MUNICIPIOS,
  WORKERS,
  PENDING_VERIFICATIONS,
  PENDING_FOLLOWUPS,
  PENDING_CONFIRMATIONS,
  CURRENT_WORKER_ID,
  TODAY,
};
